"""Actualizar relaciones a la tabla users

Revision ID: 6232bff4d4d3
Revises: 745c9cfc74e5
Create Date: 2024-10-11 18:47:27.964965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6232bff4d4d3'
down_revision = '745c9cfc74e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contacto_nombre', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('contacto_telefono', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('contacto_email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('contacto_mensaje', sa.Text(), nullable=True))

    with op.batch_alter_table('participacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participacion_uno', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('participacion_dos', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('participacion_tres', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('participacion_cuatro', sa.String(length=120), nullable=False))
        batch_op.drop_column('nombre')
        batch_op.drop_column('email')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('contacto_telefono')
        batch_op.drop_column('contacto_email')
        batch_op.drop_column('contacto_nombre')
        batch_op.drop_column('contacto_mensaje')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contacto_nombre', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('contacto_telefono', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('contacto_email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('contacto_mensaje', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('contacto_mensaje')
        batch_op.drop_column('contacto_email')
        batch_op.drop_column('contacto_telefono')
        batch_op.drop_column('contacto_nombre')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contacto_mensaje', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('contacto_nombre', sa.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('contacto_email', sa.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('contacto_telefono', sa.VARCHAR(length=15), nullable=True))

    with op.batch_alter_table('participacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('participacion_cuatro')
        batch_op.drop_column('participacion_tres')
        batch_op.drop_column('participacion_dos')
        batch_op.drop_column('participacion_uno')

    with op.batch_alter_table('contactos', schema=None) as batch_op:
        batch_op.drop_column('contacto_mensaje')
        batch_op.drop_column('contacto_email')
        batch_op.drop_column('contacto_telefono')
        batch_op.drop_column('contacto_nombre')

    # ### end Alembic commands ###
