"""Agregar campos de contacto al modelo User

Revision ID: 745c9cfc74e5
Revises: 3a22ec88fe09
Create Date: 2024-10-10 16:42:45.821847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '745c9cfc74e5'
down_revision = '3a22ec88fe09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contactos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contacto_nombre', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('contacto_telefono', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('contacto_email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('contacto_mensaje', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('contacto_mensaje')
        batch_op.drop_column('contacto_email')
        batch_op.drop_column('contacto_telefono')
        batch_op.drop_column('contacto_nombre')

    op.drop_table('event')
    op.drop_table('agent_request')
    op.drop_table('contactos')
    # ### end Alembic commands ###
